import SwiftSyntaxBuilder
import SwiftSyntax

struct RecordsFileGenerator {
    var lexicons: [Lexicon]
    var visibility: Visibility
    
    func generateRecordsFile() throws -> SourceFileSyntax {
        """
        // This file is automatically generated. Do not edit.
        // swiftlint:disable all
        // swiftformat:disable all
        
        import Foundation
        import XRPC
        import XRPCSupport
        \(generateRecordType())
        """
    }

    @CodeBlockItemListBuilder
    func generateRecordType() -> some SyntaxProtocol {
        """

        /// A collection of generic record types.
        @XRPCClosed @XRPCTag("$type")
        \(raw: visibility.rawValue) enum Record: Sendable {
        """

        for lexicon in lexicons {
            if case .record = lexicon.defs["main"] {
                """

                    @XRPCTag("\(raw: lexicon.id)")
                    case \(raw: lexicon.swiftIdentifierPrefix)(\(raw: lexicon.swiftTypeNamePrefix))
                """
            }
        }

        """

        }
        """
    }
}
